import Kissing4.Cert.OkF

-- Adapted from huwngtran/thomson-n7-lean @ 25f2fa5 (formal/lean/ThomsonN7/Solution.lean, namespace ThomsonN7):
-- `cf_sos` from `Case1.cf_sos`, `cf_ok` from `Case1.cf_ok`.
/-! Assembly of the chunked check: `Kissing4.Cert.cf.check = true`.

Generated by `lean/gen/emit_k4.py` from `numerics/kissing4/cert_D14.json` (sha256 7981aa28cd8b196d1a7a7b7240abb43ddbad419935441bf92e46a3c3f88ea7d4).
Do not edit; regenerate. -/

namespace Kissing4
namespace Cert
open ThomsonN7.Cert Kissing
/-- The positive-semidefiniteness certificates of the SOS blocks. -/
theorem cf_sos : cf.S.all (fun s => s.B.ok s.z.length) = true := by
  rw [cf_S]
  simp only [List.all_cons, List.all_nil, ok_S0, ok_S1, ok_S2, ok_S3, ok_S4, ok_S5, ok_S6, ok_S7, ok_S8, ok_S9, ok_S10, Bool.and_true]

/-- The kissing certificate passes the exact check. -/
theorem cf_ok : cf.check = true := by
  unfold CertK4.check
  rw [cf_chk, cf_blocks, cf_sos]
  decide +kernel

/-- The margin is positive. -/
theorem cf_eps_pos : 0 < cf.eps := by decide +kernel

/-- The certificate is for `25` points. -/
theorem cf_n : cf.n = 25 := rfl

end Cert
end Kissing4
