import Kissing4.Cert.ChkS10

-- Adapted from huwngtran/thomson-n7-lean @ 25f2fa5 (formal/lean/ThomsonN7/Solution.lean, namespace ThomsonN7):
-- `cf_idE_stat` from `Case1.c1_idE_stat`, `cf_chk` from `Case1.cf_chk`, `cf_K`, `cf_S`, `cf_range` from
-- `Case1.c1_K`, `Case1.c1_S`, `Case1.c1_range4`.
/-! The Kronecker check of the identity of the kissing certificate: composition of the piece statistics
(ℓ¹ < 2^95, degrees < 15, Kronecker value 0; soundness: `Kron.Ex.ev_eq_zero_of_kev`).

Generated by `lean/gen/emit_k4.py` from `numerics/kissing4/cert_D14.json` (sha256 7981aa28cd8b196d1a7a7b7240abb43ddbad419935441bf92e46a3c3f88ea7d4).
Do not edit; regenerate. -/

namespace Kissing4
namespace Cert
open ThomsonN7.Cert Kissing
theorem cf_K : cf.K = 8 := rfl

theorem cf_S : cf.S = [S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10] := rfl

theorem cf_range : List.range 8 = [0, 1, 2, 3, 4, 5, 6, 7] := rfl

/-- The statistics of the whole identity expression: `ℓ¹`-norm below `2 ^ 95`, degrees `14, 14, 14`, Kronecker value `0`. -/
theorem cf_idE_stat : ThomsonN7.Case1.c1Stat 95 15 cf.idE = (24375704014575705763529388000, 14, 14, 14, (0 : Int)) := by
  rw [kStat_idE4, cf_K, cf_S, cf_range]
  simp only [List.map_cons, List.map_nil]
  rw [stat_F0, stat_F1, stat_F2, stat_F3, stat_F4, stat_F5, stat_F6, stat_F7, stat_S0, stat_S1, stat_S2, stat_S3, stat_S4, stat_S5, stat_S6, stat_S7, stat_S8, stat_S9, stat_S10]
  decide +kernel

/-- The Kronecker check of the identity expression. -/
theorem cf_chk : chk cf.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 95 15 cf.idE
  rw [cf_idE_stat] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 24375704014575705763529388000 + 1 = 95 := by decide +kernel
  have hD : max 14 (max 14 14) + 1 = 15 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

end Cert
end Kissing4
