import Kissing4.Cert.ChkId

-- Adapted from huwngtran/thomson-n7-lean @ 25f2fa5 (formal/lean/ThomsonN7/Solution.lean, namespace ThomsonN7):
-- `cf_blocks` from `Case1.cf_blocks`.
/-! `Blk.ok` of the kernel blocks of the kissing certificate.

Generated by `lean/gen/emit_k4.py` from `numerics/kissing4/cert_D14.json` (sha256 7981aa28cd8b196d1a7a7b7240abb43ddbad419935441bf92e46a3c3f88ea7d4).
Do not edit; regenerate. -/

namespace Kissing4
namespace Cert
open ThomsonN7.Cert Kissing
/-- The positive-semidefiniteness certificates of the `F`-blocks. -/
theorem cf_blocks : (List.range cf.K).all (fun k => (cf.blk k).ok (cf.m k)) = true := by
  decide +kernel

end Cert
end Kissing4
