import Kissing.Cert.OkS10

-- Adapted from huwngtran/thomson-n7-lean @ 25f2fa5 (formal/lean/ThomsonN7/Solution.lean, namespace ThomsonN7):
-- `cf_sos` from `Case1.cf_sos`, `cf_ok` from `Case1.cf_ok`.
/-! Assembly of the chunked check: `Kissing.Cert.cf.check = true`.

Generated by `lean/gen/emit_k3.py` from `numerics/kissing3/cert_D10.json` (sha256 ea3ebae8a0f0d26e9e152b5a02cf6ea1a55f7171a9804cf82169f72cf0291183).
Do not edit; regenerate. -/

namespace Kissing
namespace Cert
open ThomsonN7.Cert
/-- The positive-semidefiniteness certificates of the SOS blocks. -/
theorem cf_sos : cf.S.all (fun s => s.B.ok s.z.length) = true := by
  rw [cf_S]
  simp only [List.all_cons, List.all_nil, ok_S0, ok_S1, ok_S2, ok_S3, ok_S4, ok_S5, ok_S6, ok_S7, ok_S8, ok_S9, ok_S10, Bool.and_true]

/-- The kissing certificate passes the exact check. -/
theorem cf_ok : cf.check = true := by
  unfold CertK.check
  rw [cf_chk, cf_blocks, cf_sos]
  decide +kernel

/-- The margin is positive. -/
theorem cf_eps_pos : 0 < cf.eps := by decide +kernel

/-- The certificate is for `13` points. -/
theorem cf_n : cf.n = 13 := rfl

end Cert
end Kissing
