import Kissing.Cert.ChkS10

-- Adapted from huwngtran/thomson-n7-lean @ 25f2fa5 (formal/lean/ThomsonN7/Solution.lean, namespace ThomsonN7):
-- `cf_idE_stat` from `Case1.c1_idE_stat`, `cf_chk` from `Case1.cf_chk`, `cf_K`, `cf_S`, `cf_range` from
-- `Case1.c1_K`, `Case1.c1_S`, `Case1.c1_range4`.
/-! The Kronecker check of the identity of the kissing certificate: composition of the piece statistics
(ℓ¹ < 2^83, degrees < 11, Kronecker value 0; soundness: `Kron.Ex.ev_eq_zero_of_kev`).

Generated by `lean/gen/emit_k3.py` from `numerics/kissing3/cert_D10.json` (sha256 ea3ebae8a0f0d26e9e152b5a02cf6ea1a55f7171a9804cf82169f72cf0291183).
Do not edit; regenerate. -/

namespace Kissing
namespace Cert
open ThomsonN7.Cert
theorem cf_K : cf.K = 6 := rfl

theorem cf_S : cf.S = [S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10] := rfl

theorem cf_range : List.range 6 = [0, 1, 2, 3, 4, 5] := rfl

/-- The statistics of the whole identity expression: `ℓ¹`-norm below `2 ^ 83`, degrees `10, 10, 10`, Kronecker value `0`. -/
theorem cf_idE_stat : ThomsonN7.Case1.c1Stat 83 11 cf.idE = (7114350894167611180577088, 10, 10, 10, (0 : Int)) := by
  rw [kStat_idE, cf_K, cf_S, cf_range]
  simp only [List.map_cons, List.map_nil]
  rw [stat_F0, stat_F1, stat_F2, stat_F3, stat_F4, stat_F5, stat_S0, stat_S1, stat_S2, stat_S3, stat_S4, stat_S5, stat_S6, stat_S7, stat_S8, stat_S9, stat_S10]
  decide +kernel

/-- The Kronecker check of the identity expression. -/
theorem cf_chk : chk cf.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 83 11 cf.idE
  rw [cf_idE_stat] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 7114350894167611180577088 + 1 = 83 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

end Cert
end Kissing
