import Kissing.Cert.ChkId

-- Adapted from huwngtran/thomson-n7-lean @ 25f2fa5 (formal/lean/ThomsonN7/Solution.lean, namespace ThomsonN7):
-- `cf_blocks` from `Case1.cf_blocks`.
/-! `Blk.ok` of the kernel blocks of the kissing certificate.

Generated by `lean/gen/emit_k3.py` from `numerics/kissing3/cert_D10.json` (sha256 ea3ebae8a0f0d26e9e152b5a02cf6ea1a55f7171a9804cf82169f72cf0291183).
Do not edit; regenerate. -/

namespace Kissing
namespace Cert
open ThomsonN7.Cert
/-- The positive-semidefiniteness certificates of the `F`-blocks. -/
theorem cf_blocks : (List.range cf.K).all (fun k => (cf.blk k).ok (cf.m k)) = true := by
  decide +kernel

end Cert
end Kissing
