import Kissing.Cert.OkF
/-! `Blk.ok` of the SOS block `S0` of the kissing certificate.

Generated by `lean/gen/emit_k3.py` from `numerics/kissing3/cert_D10.json` (sha256 ea3ebae8a0f0d26e9e152b5a02cf6ea1a55f7171a9804cf82169f72cf0291183).
Do not edit; regenerate. -/

namespace Kissing
namespace Cert
open ThomsonN7.Cert
theorem ok_S0 : S0.B.ok S0.z.length = true := by
  decide +kernel

end Cert
end Kissing
