import Mathlib
import Kissing4.Kernel  -- build order only: keeps `lake build` sequential on a shared machine

/-! The solid addition theorem on `ℝ³` for degrees `k ≤ 7`, in the normalisation of `Kissing4.Q4`

Generated by `lean/gen/gen_addition4.py` (every identity is first checked with sympy). Do not edit; regenerate.

For `y = (a, b, c)`, `y' = (a', b', c')` the kernel `Zt k`, defined by the recursion of `Kissing4.Q4` in
`w = ⟪y, y'⟫` and `g = ‖y‖² ‖y'‖²`, equals `∑_{m ≤ k} coefK k m · A k m y · A k m y' · Rc m`, where
`Rc m = Re((a + i b)^m (a' - i b')^m)` (Chebyshev recursion), `A k m (a, b, c) = r^(k-m) P_k^(m)(c / r)`
(`P_k` the Legendre polynomial, `r² = a² + b² + c²`; a polynomial in `c` and `r²`) and
`coefK k m = k! · (m = 0 ? 1 : 2 (k-m)! / (k+m)!) ≥ 0`. -/

namespace Kissing4

/-- The `k!`-scaled solid Legendre kernel on `ℝ³`, by the recursion of `Q4`. -/
noncomputable def Zt (a b c a' b' c' : ℝ) : ℕ → ℝ
  | 0 => 1
  | 1 => a * a' + b * b' + c * c'
  | k + 2 => (2 * (k : ℝ) + 3) * (a * a' + b * b' + c * c') * Zt a b c a' b' c' (k + 1)
      - ((k : ℝ) + 1) ^ 2 * ((a ^ 2 + b ^ 2 + c ^ 2) * (a' ^ 2 + b' ^ 2 + c' ^ 2)) * Zt a b c a' b' c' k

/-- `Re((a + i b)^m (a' - i b')^m)`, by the Chebyshev recursion. -/
noncomputable def Rc (a b a' b' : ℝ) : ℕ → ℝ
  | 0 => 1
  | 1 => a * a' + b * b'
  | m + 2 => 2 * (a * a' + b * b') * Rc a b a' b' (m + 1) - (a ^ 2 + b ^ 2) * (a' ^ 2 + b' ^ 2) * Rc a b a' b' m

/-- The polynomial factors `A k m (a, b, c) = r^(k-m) P_k^(m)(c / r)` for `m ≤ k ≤ 7` (`0` otherwise). -/
noncomputable def Aa : ℕ → ℕ → ℝ → ℝ → ℝ → ℝ
  | 0, 0, _, _, _ => 1
  | 1, 0, _, _, c => c
  | 1, 1, _, _, _ => 1
  | 2, 0, a, b, c => -a^2/2 - b^2/2 + c^2
  | 2, 1, _, _, c => 3*c
  | 2, 2, _, _, _ => 3
  | 3, 0, a, b, c => -3*a^2*c/2 - 3*b^2*c/2 + c^3
  | 3, 1, a, b, c => -3*a^2/2 - 3*b^2/2 + 6*c^2
  | 3, 2, _, _, c => 15*c
  | 3, 3, _, _, _ => 15
  | 4, 0, a, b, c => 3*a^4/8 + 3*a^2*b^2/4 - 3*a^2*c^2 + 3*b^4/8 - 3*b^2*c^2 + c^4
  | 4, 1, a, b, c => -15*a^2*c/2 - 15*b^2*c/2 + 10*c^3
  | 4, 2, a, b, c => -15*a^2/2 - 15*b^2/2 + 45*c^2
  | 4, 3, _, _, c => 105*c
  | 4, 4, _, _, _ => 105
  | 5, 0, a, b, c => 15*a^4*c/8 + 15*a^2*b^2*c/4 - 5*a^2*c^3 + 15*b^4*c/8 - 5*b^2*c^3 + c^5
  | 5, 1, a, b, c => 15*a^4/8 + 15*a^2*b^2/4 - 45*a^2*c^2/2 + 15*b^4/8 - 45*b^2*c^2/2 + 15*c^4
  | 5, 2, a, b, c => -105*a^2*c/2 - 105*b^2*c/2 + 105*c^3
  | 5, 3, a, b, c => -105*a^2/2 - 105*b^2/2 + 420*c^2
  | 5, 4, _, _, c => 945*c
  | 5, 5, _, _, _ => 945
  | 6, 0, a, b, c => -5*a^6/16 - 15*a^4*b^2/16 + 45*a^4*c^2/8 - 15*a^2*b^4/16 + 45*a^2*b^2*c^2/4 - 15*a^2*c^4/2 - 5*b^6/16 + 45*b^4*c^2/8 - 15*b^2*c^4/2 + c^6
  | 6, 1, a, b, c => 105*a^4*c/8 + 105*a^2*b^2*c/4 - 105*a^2*c^3/2 + 105*b^4*c/8 - 105*b^2*c^3/2 + 21*c^5
  | 6, 2, a, b, c => 105*a^4/8 + 105*a^2*b^2/4 - 210*a^2*c^2 + 105*b^4/8 - 210*b^2*c^2 + 210*c^4
  | 6, 3, a, b, c => -945*a^2*c/2 - 945*b^2*c/2 + 1260*c^3
  | 6, 4, a, b, c => -945*a^2/2 - 945*b^2/2 + 4725*c^2
  | 6, 5, _, _, c => 10395*c
  | 6, 6, _, _, _ => 10395
  | 7, 0, a, b, c => -35*a^6*c/16 - 105*a^4*b^2*c/16 + 105*a^4*c^3/8 - 105*a^2*b^4*c/16 + 105*a^2*b^2*c^3/4 - 21*a^2*c^5/2 - 35*b^6*c/16 + 105*b^4*c^3/8 - 21*b^2*c^5/2 + c^7
  | 7, 1, a, b, c => -35*a^6/16 - 105*a^4*b^2/16 + 105*a^4*c^2/2 - 105*a^2*b^4/16 + 105*a^2*b^2*c^2 - 105*a^2*c^4 - 35*b^6/16 + 105*b^4*c^2/2 - 105*b^2*c^4 + 28*c^6
  | 7, 2, a, b, c => 945*a^4*c/8 + 945*a^2*b^2*c/4 - 630*a^2*c^3 + 945*b^4*c/8 - 630*b^2*c^3 + 378*c^5
  | 7, 3, a, b, c => 945*a^4/8 + 945*a^2*b^2/4 - 4725*a^2*c^2/2 + 945*b^4/8 - 4725*b^2*c^2/2 + 3150*c^4
  | 7, 4, a, b, c => -10395*a^2*c/2 - 10395*b^2*c/2 + 17325*c^3
  | 7, 5, a, b, c => -10395*a^2/2 - 10395*b^2/2 + 62370*c^2
  | 7, 6, _, _, c => 135135*c
  | 7, 7, _, _, _ => 135135
  | _, _, _, _, _ => 0

/-- The coefficients `k! · c_{k,m}` for `m ≤ k ≤ 7` (`0` otherwise). -/
noncomputable def coefK : ℕ → ℕ → ℝ
  | 0, 0 => 1
  | 1, 0 => 1
  | 1, 1 => 1
  | 2, 0 => 2
  | 2, 1 => 2/3
  | 2, 2 => 1/6
  | 3, 0 => 6
  | 3, 1 => 1
  | 3, 2 => 1/10
  | 3, 3 => 1/60
  | 4, 0 => 24
  | 4, 1 => 12/5
  | 4, 2 => 2/15
  | 4, 3 => 1/105
  | 4, 4 => 1/840
  | 5, 0 => 120
  | 5, 1 => 8
  | 5, 2 => 2/7
  | 5, 3 => 1/84
  | 5, 4 => 1/1512
  | 5, 5 => 1/15120
  | 6, 0 => 720
  | 6, 1 => 240/7
  | 6, 2 => 6/7
  | 6, 3 => 1/42
  | 6, 4 => 1/1260
  | 6, 5 => 1/27720
  | 6, 6 => 1/332640
  | 7, 0 => 5040
  | 7, 1 => 180
  | 7, 2 => 10/3
  | 7, 3 => 1/15
  | 7, 4 => 1/660
  | 7, 5 => 1/23760
  | 7, 6 => 1/617760
  | 7, 7 => 1/8648640
  | _, _ => 0

theorem coefK_nonneg (k m : ℕ) : 0 ≤ coefK k m := by
  unfold coefK
  split <;> norm_num

theorem Zt_addition_0 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 0 = ∑ m ∈ Finset.range 1,
      coefK 0 m * Aa 0 m a b c * Aa 0 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  ring

theorem Zt_addition_1 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 1 = ∑ m ∈ Finset.range 2,
      coefK 1 m * Aa 1 m a b c * Aa 1 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  ring

theorem Zt_addition_2 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 2 = ∑ m ∈ Finset.range 3,
      coefK 2 m * Aa 2 m a b c * Aa 2 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  push_cast
  ring

theorem Zt_addition_3 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 3 = ∑ m ∈ Finset.range 4,
      coefK 3 m * Aa 3 m a b c * Aa 3 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  push_cast
  ring

theorem Zt_addition_4 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 4 = ∑ m ∈ Finset.range 5,
      coefK 4 m * Aa 4 m a b c * Aa 4 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  push_cast
  ring

theorem Zt_addition_5 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 5 = ∑ m ∈ Finset.range 6,
      coefK 5 m * Aa 5 m a b c * Aa 5 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  push_cast
  ring

theorem Zt_addition_6 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 6 = ∑ m ∈ Finset.range 7,
      coefK 6 m * Aa 6 m a b c * Aa 6 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  push_cast
  ring

theorem Zt_addition_7 (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' 7 = ∑ m ∈ Finset.range 8,
      coefK 7 m * Aa 7 m a b c * Aa 7 m a' b' c' * Rc a b a' b' m := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Zt, Rc, Aa, coefK]
  push_cast
  ring

/-- **The addition theorem for `k ≤ 7`.** -/
theorem Zt_addition {k : ℕ} (hk : k ≤ 7) (a b c a' b' c' : ℝ) :
    Zt a b c a' b' c' k = ∑ m ∈ Finset.range (k + 1),
      coefK k m * Aa k m a b c * Aa k m a' b' c' * Rc a b a' b' m := by
  interval_cases k
  · exact Zt_addition_0 a b c a' b' c'
  · exact Zt_addition_1 a b c a' b' c'
  · exact Zt_addition_2 a b c a' b' c'
  · exact Zt_addition_3 a b c a' b' c'
  · exact Zt_addition_4 a b c a' b' c'
  · exact Zt_addition_5 a b c a' b' c'
  · exact Zt_addition_6 a b c a' b' c'
  · exact Zt_addition_7 a b c a' b' c'

end Kissing4
